name: Deploy to DigitalOcean

on:
  push:
    branches:
      - oluwatobi  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change this to your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to DigitalOcean
      run: |
        ssh-keyscan -H ${{ secrets.WEB_APP_SSH_HOST }} >> $HOME/.ssh/known_hosts
        ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.WEB_APP_SSH_USERNAME }}@${{ secrets.WEB_APP_SSH_HOST }} 'bash -s' <<'ENDSSH'
          # Replace with your deployment steps, e.g., stop the existing service, copy new files, and start the service.
          cd /path/to/your/app
          git pull
          npm install
          npm run build
          # Restart your web server, e.g., Nginx or Apache
          sudo systemctl restart nginx
        ENDSSH
